### ISSUE TITLE
Create Sales Order App with SAP RAD by Mendix

### ISSUE THREAD

**Issue by npansap** [sap-tutorials/Issues#394]
Tutorials: https://developers.sap.com/tutorials/mendix-salesorders.html
--------------------------

On step 3 "Import module in Mendix app", I get an error trying to import the .mpk file generated from the previous step (screenshot attached).  I can't seem to find a compatible version of the OData Model Creator - there is only the one (outdated) version online, and it appears not to be available as an app within the Studio Pro desktop app.  

![image](https://user-images.githubusercontent.com/41884090/120037259-54656a00-bfcf-11eb-87ce-6b2429c9e661.png)

**Comment by Paolaufer** [comment]
HI,
I've sent this to the developers and hope to have a reply for you soon.
I will keep you updated.

**Comment by MichaelCzcz** [comment]
@Paolaufer Any updates?

**Comment by Paolaufer** [comment]
Sorry, not yet.

**Comment by Paolaufer** [comment]
Sorry, I was unable to reproduce the error.
I will close the ticket.

If you encounter this again, please open a new ticket.
