### ISSUE TITLE
Refine the List Report with Additional Annotations

### ISSUE THREAD

**Issue by d023604** [sap-tutorials/Issues#399]
Tutorials: https://developers.sap.com/tutorials/fiori-tools-cap-modify-list-report.html
--------------------------

Just a minor improvement - In Step 4 - the text says to set the Initial Load property to True - as shown in the image accompanying the text.

In SAP Fiori Tools 1.2.0 in Visual Code, the Initial Load property has four permitted values: space, Auto, Enabled, Disabled.

Suggest adjusting the Step 4 image and text to say set the Initial Load property to Enabled

**Comment by jofiess** [comment]
Hello Andrew,
thank you for the hint. We a currently in the process to update and adjust the tutorial to the latest changes of the Fiori tools.
Best regards
Joachim

**Comment by iwonahahn** [comment]
Hi @d023604,

Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. If you still have questions, feel free to reopen the issue.

Best regards,
Iwona
