### ISSUE TITLE
Get Started with SAP Workflow Service

### ISSUE THREAD

**Issue by ubabap** [sap-tutorials/Issues#418]
Group: https://developers.sap.com/group.cp-workflow-cf.html
--------------------------

Hello together.
First: The setup process , especially wiht the booster is smooth as it should be.

But i am missing the maybe most central point in this turorial, is that it does never explain, who will see the Items  and it is created to only send to the initiator itself.  (The same for  some other beginner tutorial , where the same process is even just uploaded form GitHub. and where i will add the same comment)
Even for the most simple Workflow as a beginner the major point is sending it out to a group of other persons, that are doing an approval or whatever. I think it should be extended to allow another user than the initiator to see it in the inbox.
(i actually faked that by adding a field for it in the Start Form and putting it somewhere in the context  and add that to the recipients in the user form for the decision as recipient.  For sure this can be set up better. But wihtout, the whole workflow principal seems ot be spoiled. )
Also there is no explanation to anything that has been done:
Which fields are available out of the environment -> Link to a help or more in depth other tutorial or whatever )

**Comment by AstridHerbst** [comment]
Thank you for your feedback. I will align with my colleagues on this.

**Comment by MichaelCzcz** [comment]
@AstridHerbst Any updates?

**Comment by iwonahahn** [comment]
Hi @ubabap,

Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. If you still have questions, feel free to open a new one.

Best regards,
Iwona
