### ISSUE TITLE
Bundle Sensor Data in SAP Data Intelligence, Trial Edition

### ISSUE THREAD

**Issue by thanasitv** [sap-tutorials/Issues#530]
Tutorials: https://developers.sap.com/tutorials/dataintelligence-trial-v2-pipelines-part03.html
--------------------------

Write here how you think we can improve the tutorial ...

I can not find JS String Operator from SAP Data Intelligence, trial edition 3.1 from 
(Deploy from Cloud Appliance Library to MS Azure kubernetes)

I tried to use Javascript(v2) Operator and put the code in this operator but when run the process is dead with message

Message
Group messages:
Group: default; Messages: Graph failure: Port input1 not found
Process(es) terminated with error(s). restartOnFailure==false

Best Regards,
Thanasit V.
![CannotFindJSStringOperator](https://user-images.githubusercontent.com/31183618/128285153-9068ecb4-1426-4419-a1f3-15fe2b5eeb97.png)
![Add JS String Operator](https://user-images.githubusercontent.com/31183618/128285156-51811922-898f-4c2a-8a67-e5f2e942c72d.png)
![SAP_Cloud_Appliance_SAP_DataIntelligence](https://user-images.githubusercontent.com/31183618/128285159-347f381a-d433-4509-bf03-732a4cdabe38.png)

**Comment by thanasitv** [comment]
![ProcessDeadWithErrMsg](https://user-images.githubusercontent.com/31183618/128285246-1926ba83-631e-418c-bd6a-d7eb18c7ac47.png)

**Comment by NikhilD16** [comment]
The callback output port needs to point to input1 like   $.setPortCallback("input1",onInput);

You can refer to the latest update on the portal.
