### ISSUE TITLE
Create Workflow (part 1), Enrich Data With Data Transform in SAP Data Intelligence, Trial Edition

### ISSUE THREAD

**Issue by mata-r** [sap-tutorials/Issues#554]
Tutorials: https://developers.sap.com/tutorials/dataintelligence-trial-v2-workflow-part01.html
--------------------------

This tutorial is referencing deprecated objects, like "Spark Data Transform" the problem is that the new object is incompatible; in this example new "Data Transform" operator needs a "table" type; if you follow this tutorial, you don't get this input. You could say the tutorial has become obsolete as part of the mission.

**Comment by NikhilD16** [comment]
I will check and get back on this

**Comment by NikhilD16** [comment]
As of January 31, 2023, the DI Trial CAL image is no longer available. If you are using the trial as an existing SAP customer, please reach out to your account executive and work with them to explore different options available to you.

Refer to the blog https://blogs.sap.com/2022/07/14/sap-data-intelligence-trial-edition-3.2/
