### ISSUE TITLE
Create a Custom UI for SAP S/4HANA Cloud

### ISSUE THREAD

**Issue by matbeerkens** [sap-tutorials/Issues#611]
Group: https://developers.sap.com/group.abap-custom-ui-s4hana-cloud.html
--------------------------

Hi colleagues, i think that the **name** of this group is _misleading_. You **cannot** just create a custom UI for any API in S/4HC. This is purely a UI for a _Custom Business Object_, for which we also have an _option directly in the Custom Business Object itself_.
Although part of that information is present here: [https://developers.sap.com/tutorials/abap-custom-ui-bas-develop-s4hc.html](https://developers.sap.com/tutorials/abap-custom-ui-bas-develop-s4hc.html)

I think it needs to be made much more clear.

**Comment by Liebherr** [comment]
Hi Mat,
thanks for the feedback and sorry for the late reply. The group name does not come from building a custom UI on any S4HC API, but from doing this for custom business objects in(!) S4HC. This is clearly told by all descriptions and I cannot imagine that people start interpreting the group name in a contrary direction.
Thanks and Regards
Ulrike
