### ISSUE TITLE
Create a UI Using Freestyle SAPUI5

### ISSUE THREAD

**Issue by LotharBender** [sap-tutorials/Issues#637]
Tutorials: https://developers.sap.com/tutorials/btp-app-create-ui-freestyle-sapui5.html
--------------------------

The file `ui5.yaml` mentioned in `Step 4: (Optional) SAPUI5 serve` does not exist - neither in the `mitigations` app folder nor in the `risks` app folder. It seems that this file is no longer generated by the `Fiori Application Generator` I am using version 1.3.5

Regards,
Lothar

**Comment by draschke** [comment]
Hi all,
will only let you know, that I've the same issue.
![image](https://user-images.githubusercontent.com/4199123/136964218-d8542686-c59b-4265-80e2-6f1ff2197199.png)
Regards, Dirk
