### ISSUE TITLE
Devtoberfest - Week 1 - Speaker

### ISSUE THREAD

**Issue by Ngugisenior** [sap-tutorials/Issues#638]
Tutorials: https://developers.sap.com/tutorials/devtoberfest-week-1-speaker.html
--------------------------

Already watched the video but was unable to mark it as complete. no option to mark it as done 
![devtober1](https://user-images.githubusercontent.com/25932594/136252024-9ad38b8c-df84-48fe-b6c5-3cab32476141.PNG)

**Comment by Ngugisenior** [comment]
thanks works now

**Comment by jung-thomas** [comment]
Thanks for reporting the issue.  It should be corrected now. Sounds like you already retried and it did work. That's great!
