### ISSUE TITLE
Create a UI Using Freestyle SAPUI5

### ISSUE THREAD

**Issue by CJSwift** [sap-tutorials/Issues#651]
Tutorials: https://developers.sap.com/tutorials/btp-app-create-ui-freestyle-sapui5.html
--------------------------

In the optional Step 4 (for Windows) the fourth instruction asks the user to add the ui5-middleware-simpleproxy and ui5-middleware-livereload lines

From my experience following this, if you add these without removing the existing fiori lines, then using ui5 serve later on will not be successful. The existing entries in this ui5.yaml file need to be removed first. It could be helpful to point this out

**Comment by stijnme** [comment]
Correct, also the `package.json` looks a bit different.
My excercise/state of files can be found in following commit: [btp-application-cap-e2e](https://github.com/stijnme/btp-application-cap-e2e/commit/74d9bfb1c99f298d0a97a0530e7fd7f65d1b17d9#diff-53a8457f1d2805781e59df2eacce909d631c00ab114c5a4bba9f905136946d71
)

In short, `package.json`:
- add both ui5 middleware modules
- add the ui5 dependency block

As mentioned by CJSwift, delete the fiori tools config in `ui5.yalm` and add the middleware configuration.
