### ISSUE TITLE
Set Up the SAP HANA Cloud Service

### ISSUE THREAD

**Issue by ceedee666** [sap-tutorials/Issues#669]
Tutorials: https://developers.sap.com/tutorials/btp-app-hana-cloud-setup.html
--------------------------
The JSON snippet in step 1 has a small issue with indentation.
Correct would be:

```json
{
    "name": "cpapp",
    ...
    "cds": {
        "requires": {
            "db": {
                "kind": "sql"
              }
          },
        "hana": {
            "deploy-format": "hdbtable"
        }
    }
}
```

**Comment by slavipande** [comment]
Hi @ceedee666 ,

Thanks for your feedback!

The indentation issue is fixed and should be visible when merged. 
Hence, I'll be closing this issue.

Best regards,
Svetoslav
