### ISSUE TITLE
Add a List Report Interface to the CAP App (SAP HANA Cloud)

### ISSUE THREAD

**Issue by joschindlbeck** [sap-tutorials/Issues#685]
Tutorials: https://developers.sap.com/tutorials/hana-cloud-cap-add-list-report.html
--------------------------

Hi SAP team,
thanks for this fantastic tutorial!
May you please check Step 2, section 2? For me adding "&$search=DE" did not work, adding "?$search=DE" did the trick.
Best regards,
Johannes

**Comment by IObert** [comment]
Good catch! The `&` only works if there is already another used parameter before it which used teh `?`.

I just fixed it and the result should be live within the next few minutes.
