### ISSUE TITLE
Create Queues and Queue Subscriptions for SAP Event Mesh

### ISSUE THREAD

**Issue by lfuster** [sap-tutorials/Issues#704]
I already created a Event Mesh service instance on default plan, but I cannot see the option of standard plan to subscribe to event mesh

**Comment by iwonahahn** [comment]
Hi @lfuster,

You are not referring to a tutorial. Therefore we can not assign your issue to an author. We close this issue here and would ask you to open a new one [here](https://github.com/sap-tutorials/Tutorials/issues) providing a link to a step/tutorial.

Best regards,
Iwona
