### ISSUE TITLE
Create Your First ABAP Console Application

### ISSUE THREAD

**Issue by marianfoo** [sap-tutorials/Issues#709]
https://developers.sap.com/tutorials/abap-environment-console-application.html#742a4005-c060-44e7-9012-39ef914d0a0d
The Answer on the Test is wrong.
The wrong answer saved here is :
`out->write('Hello SAP Cloud Platform ABAP Environment!').`
The correct answer is:
`out->write( 'Hello SAP Cloud Platform ABAP Environment!' ).`

Wrong whitespaces already mentioned here: https://github.com/sap-tutorials/Issues/issues/635

Also at Step 5 there is still a wrong statement: `out->write('Hello World!').` without whitespaces.

**Comment by MichaelCzcz** [comment]
@marianfoo Thank you for your feedback. This repository is no longer used for posting issues. Please post future issues via the "Feedback" function in the top right area of the tutorial page.

![image](https://user-images.githubusercontent.com/57144076/194863397-699bcc6c-9569-488e-99d5-ca6fc2d22165.png)

**Comment by marianfoo** [comment]
https://github.com/sap-tutorials/Tutorials/issues/18858
