### ISSUE TITLE
ERROR: Failed to register "SystemDB" database to Cockpit

### ISSUE THREAD

**Issue by Harlequin8x** [sap-tutorials/Issues#713]
Hi,

I'm very new to SAP and Linux and after several trys to install SAP from the mainpage that didn't work out, I tried to use HANA 2.0 Epxress Edition with VirtualBox. 
This is a nightmare to install. After fixing a problem, the next problem comes around. I only found one forum threat about this problem, but didn't help me at all. When I read deactivate your firewall, I can just shake my head and wonder how you can even suggest such thing.
I appreciate any help!

![Clipboard02sdfsdf](https://user-images.githubusercontent.com/96945956/209315843-3d01f89a-d8de-4ea1-be80-78811ac7842f.jpg)

**Comment by MichaelCzcz** [comment]
These GitHub issues are to resolve issues (i.e., problems/errors) with the tutorials. Your question seems more general and likely 
would get more visibility -- and a better answer -- in the SAP Community's Questions & Answers. You can ask your question at:
https://answers.sap.com/index.html

**Comment by Harlequin8x** [comment]
Sorry about that. Thank you for the link.
